# Generated by Django 4.2.18 on 2025-06-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('freeze', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
                ('modify_by', models.CharField(default='', max_length=255)),
                ('work_directory', models.CharField(max_length=255)),
                ('cas_temp_repertory', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=255)),
                ('work_directory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RevueVeine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilitaireConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genepi_path', models.CharField(blank=True, max_length=255, null=True)),
                ('canelle_path', models.CharField(blank=True, max_length=255, null=True)),
                ('pta_path', models.CharField(blank=True, max_length=255, null=True)),
                ('anNA_path', models.CharField(blank=True, max_length=255, null=True)),
                ('carma_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ensight_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ffro_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsoVitesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='black', max_length=255)),
                ('file_type', models.CharField(choices=[('Excel', 'Excel'), ('hdf', 'hdf')], default='Excel', max_length=20)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etat')),
            ],
        ),
        migrations.AddField(
            model_name='etat',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project'),
        ),
        migrations.CreateModel(
            name='Cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('used', models.BooleanField(default=True)),
                ('file_path', models.CharField(max_length=255)),
                ('select', models.BooleanField(default=False)),
                ('bsam_path', models.CharField(blank=True, max_length=255, null=True)),
                ('repertory', models.CharField(blank=True, max_length=255, null=True)),
                ('iso_vitesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.isovitesse')),
            ],
        ),
        migrations.CreateModel(
            name='Bsam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('used', models.BooleanField(default=True)),
                ('line_style', models.CharField(choices=[('-', 'Solid'), ('--', 'Dashed'), ('-.', 'Dashdot'), (':', 'Dotted'), ('', 'None')], default='-', max_length=20)),
                ('couleur', models.CharField(choices=[('0,0,0', 'Noir'), ('255,0,0', 'Rouge'), ('0,128,0', 'Vert'), ('0,0,255', 'Bleu'), ('255,165,0', 'Orange'), ('255,0,255', 'Magenta'), ('255,255,0', 'Jaune'), ('128,0,128', 'Violet'), ('0,255,255', 'Cyan'), ('192,192,192', 'Gris Clair'), ('128,128,128', 'Gris'), ('255,192,203', 'Rose')], default='0,0,255', max_length=20)),
                ('etat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etat')),
                ('revue_veine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.revueveine')),
            ],
        ),
    ]
