# Generated by Django 4.2.18 on 2025-06-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitaireconfiguration',
            name='ffro_path',
        ),
        migrations.RemoveField(
            model_name='utilitaireconfiguration',
            name='pta_path',
        ),
        migrations.AlterField(
            model_name='bsam',
            name='couleur',
            field=models.CharField(choices=[('0,0,0', 'Noir'), ('255,0,0', 'Rouge'), ('0,0,255', 'Bleu'), ('0,128,0', 'Vert'), ('128,0,128', 'Violet'), ('255,192,203', 'Rose'), ('255,165,0', 'Orange'), ('255,255,0', 'Jaune'), ('255,69,0', 'Rouge orangé'), ('128,0,0', 'Bordeaux'), ('128,128,128', 'Gris'), ('0,255,255', 'Cyan'), ('0,0,139', 'Bleu foncé'), ('65,105,225', 'Bleu royal'), ('173,216,230', 'Bleu clair'), ('144,238,144', 'Vert clair'), ('0,100,0', 'Vert foncé'), ('0,139,139', 'Cyan foncé'), ('165,42,42', 'Brun')], default='0,0,255', max_length=20),
        ),
    ]
