# Generated by Django 4.2.18 on 2025-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_utilitaireconfiguration_ffro_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitaireconfiguration',
            name='user_config',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
