# Generated by Django 4.2.18 on 2025-06-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_utilitaireconfiguration_user_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilitaireconfiguration',
            old_name='canelle_path',
            new_name='cannelle_path',
        ),
    ]
