# Generated by Django 4.2.18 on 2025-06-27 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_rename_canelle_path_utilitaireconfiguration_cannelle_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitaireconfiguration',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
