# Generated by Django 4.2.18 on 2025-06-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_utilitaireconfiguration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitaireconfiguration',
            name='user_config',
        ),
    ]
