# Generated by Django 4.2.18 on 2025-07-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_utilitaireconfiguration_user_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsam',
            name='marker',
            field=models.CharField(choices=[('o', 'Circle'), ('s', 'Square'), ('^', 'Triangle Up'), ('v', 'Triangle Down'), ('x', 'X'), ('+', 'Plus'), ('*', 'Star'), ('', 'None')], default='o', max_length=10),
        ),
        migrations.AlterField(
            model_name='isovitesse',
            name='file_type',
            field=models.CharField(choices=[('Excel', 'Excel'), ('hdf', 'hdf (.trac)')], default='Excel', max_length=20),
        ),
    ]
