# Generated by Django 4.2.18 on 2025-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bsam_marker_alter_isovitesse_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsam',
            name='marker',
            field=models.CharField(choices=[('circle', 'Cercle (o)'), ('square', 'Carré (s)'), ('triangle', 'Triangle haut (^)'), ('inverted_triangle', 'Triangle bas (v)'), ('x', 'X'), ('cross', 'Croix (+)'), ('asterisk', 'Étoile (*)'), ('hex', 'Hexagone')], default='o', max_length=255),
        ),
    ]
