# Generated by Django 4.2.18 on 2025-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bsam_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='isovitesse',
            name='marker',
            field=models.CharField(choices=[('circle', 'Cercle (o)'), ('square', 'Carré (s)'), ('triangle', 'Triangle haut (^)'), ('inverted_triangle', 'Triangle bas (v)'), ('x', 'X'), ('cross', 'Croix (+)'), ('asterisk', 'Étoile (*)'), ('hex', 'Hexagone')], default='circle', max_length=255),
        ),
        migrations.AlterField(
            model_name='bsam',
            name='marker',
            field=models.CharField(choices=[('circle', 'Cercle (o)'), ('square', 'Carré (s)'), ('triangle', 'Triangle haut (^)'), ('inverted_triangle', 'Triangle bas (v)'), ('x', 'X'), ('cross', 'Croix (+)'), ('asterisk', 'Étoile (*)'), ('hex', 'Hexagone')], default='circle', max_length=255),
        ),
    ]
