# Generated by Django 4.2.18 on 2025-07-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_isovitesse_marker_alter_bsam_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsam',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
