# Generated by Django 4.2.18 on 2025-07-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bsam_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='cas',
            name='obj_type',
            field=models.CharField(choices=[('cas_cannelle', 'Cas Cannelle'), ('bsam', 'bsam')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
