# Generated by Django 4.2.18 on 2025-07-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cas_obj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='etat',
            name='bsam_temp_repertory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cas',
            name='obj_type',
            field=models.CharField(choices=[('cas_cannelle', 'Cas Cannelle'), ('bsam', 'bsam')], default='cas_cannelle', max_length=20),
        ),
    ]
