# Generated by Django 4.2.18 on 2025-07-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_etat_bsam_temp_repertory_alter_cas_obj_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isovitesse',
            name='file_type',
            field=models.CharField(choices=[('Excel', 'Excel'), ('hdf', 'hdf (.trac)'), ('bsam', 'bsam (.bsam)')], default='Excel', max_length=20),
        ),
    ]
