# Generated by Django 4.2.18 on 2025-07-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_isovitesse_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flux', models.IntegerField()),
                ('position', models.IntegerField()),
                ('omega', models.FloatField()),
                ('nb_blade', models.IntegerField()),
                ('bsam_name', models.CharField(max_length=255)),
                ('bsam_name_alias', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(editable=False, max_length=10)),
                ('bsam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bsam')),
            ],
        ),
        migrations.AddField(
            model_name='cas',
            name='calculate_perfo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='isovitesse',
            name='row_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='isovitesse',
            name='file_type',
            field=models.CharField(choices=[('excel', 'Excel (.xls)'), ('hdf', 'hdf (.trac)'), ('bsam', 'Bsam (.bsam)')], default='Excel', max_length=20),
        ),
        migrations.CreateModel(
            name='RowPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Qcorr_ref', models.FloatField(null=True)),
                ('Pi', models.FloatField(null=True)),
                ('Etapol', models.FloatField(null=True)),
                ('Qcorr', models.FloatField(null=True)),
                ('Cd', models.FloatField(null=True)),
                ('PisQcorr_ref', models.FloatField(null=True)),
                ('entry_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_entry', to='main.row')),
                ('exit_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_exit', to='main.row')),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='cas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cas'),
        ),
    ]
