# Generated by Django 4.2.18 on 2025-07-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_row_cas_calculate_perfo_isovitesse_row_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='bsam',
        ),
        migrations.RemoveField(
            model_name='row',
            name='bsam_name',
        ),
        migrations.RemoveField(
            model_name='row',
            name='bsam_name_alias',
        ),
        migrations.RemoveField(
            model_name='row',
            name='cas',
        ),
        migrations.RemoveField(
            model_name='rowpair',
            name='entry_row',
        ),
        migrations.RemoveField(
            model_name='rowpair',
            name='exit_row',
        ),
        migrations.AddField(
            model_name='rowpair',
            name='bsam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bsam'),
        ),
        migrations.AddField(
            model_name='rowpair',
            name='cas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cas'),
        ),
    ]
