# Generated by Django 4.2.18 on 2025-07-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_row_bsam_remove_row_bsam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowpair',
            name='Tau',
            field=models.FloatField(null=True),
        ),
    ]
