# Generated by Django 4.2.18 on 2025-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rowpair_tau'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowpair',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
