# Generated by Django 4.2.18 on 2025-07-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rowpair_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='row_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cas'),
        ),
    ]
