# Generated by Django 4.2.18 on 2025-07-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_row_row_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='bsam_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
