# Generated by Django 4.2.18 on 2025-07-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_row_bsam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='flux',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='row_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rowpair'),
        ),
    ]
