# Generated by Django 4.2.18 on 2025-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_row_flux_alter_row_row_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='cas',
            name='row_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='row',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
