# Generated by Django 4.2.18 on 2025-07-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_cas_row_data_row_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cas',
            old_name='row_data',
            new_name='row_metadata',
        ),
    ]
