# Generated by Django 4.2.18 on 2025-07-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_row_data_cas_row_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='row_pair',
        ),
        migrations.AddField(
            model_name='row',
            name='cas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cas'),
        ),
        migrations.AddField(
            model_name='rowpair',
            name='entry_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_entry_row', to='main.row'),
        ),
        migrations.AddField(
            model_name='rowpair',
            name='exit_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_exit_row', to='main.row'),
        ),
    ]
