# Generated by Django 4.2.18 on 2025-07-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_row_row_pair_row_cas_rowpair_entry_row_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rowpair',
            name='bsam',
        ),
        migrations.AddField(
            model_name='cas',
            name='revue_veine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.revueveine'),
        ),
        migrations.DeleteModel(
            name='Bsam',
        ),
    ]
