# Generated by Django 4.2.18 on 2025-07-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_rowpair_bsam_cas_revue_veine_delete_bsam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas',
            name='iso_vitesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.isovitesse'),
        ),
    ]
