# Generated by Django 4.2.18 on 2025-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_cas_iso_vitesse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cas",
            name="obj_type",
            field=models.CharField(
                choices=[("cas_cannelle", "Cas Cannelle"), ("bsam", "Cas BSAM")],
                default="cas_cannelle",
                max_length=20,
            ),
        ),
    ]
