# Generated by Django 4.2.18 on 2025-08-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_add_pisqcorr_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='revueveine',
            name='directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='isovitesse',
            name='marker',
            field=models.CharField(choices=[('circle', 'Cercle ●'), ('square', 'Carré ■'), ('triangle', 'Triangle Haut ▲'), ('inverted_triangle', 'Triangle Bas ▼'), ('x', 'Croix ✕'), ('cross', 'Plus ✚'), ('asterisk', 'Étoile ✱'), ('hex', 'Hexagone ⬡')], default='circle', max_length=255),
        ),
    ]
