# Generated by Django 4.2.18 on 2025-08-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_revueveine_directory_alter_isovitesse_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='isovitesse',
            name='recalage_kd',
            field=models.FloatField(default=1),
        ),
    ]
