# Generated by Django 4.2.18 on 2025-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_isovitesse_recalage_kd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isovitesse",
            name="recalage_kd",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
