# Generated by Django 4.2.18 on 2025-08-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_isovitesse_recalage_kd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas',
            name='obj_type',
            field=models.CharField(choices=[('cas_cannelle', 'Cas Cannelle'), ('bsam', 'Cas Bsam'), ('cas_utilisateur', 'Cas Utilisateur')], default='cas_cannelle', max_length=20),
        ),
    ]
