# Generated by Django 4.2.18 on 2025-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_cas_obj_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='nb_blade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='omega',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
