# Generated by Django 4.2.18 on 2025-08-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_row_nb_blade_alter_row_omega'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevueAube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directory', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
