# Generated by Django 4.2.18 on 2025-09-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_revueaube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple')], default='red', max_length=20)),
                ('projet_version_aube', models.CharField(blank=True, default='CME3/S1/S1AB', max_length=100)),
                ('type_coupe_nbre_ldc', models.CharField(blank=True, default='CQ29', max_length=50)),
                ('coupe_dessin', models.CharField(blank=True, default='1,11,15,19,29', max_length=200)),
                ('label_bsam', models.CharField(blank=True, default='S1', max_length=50)),
                ('inversion_aube', models.BooleanField(default=False)),
                ('fichier_bsam', models.CharField(blank=True, max_length=255)),
                ('inversion_bsam', models.BooleanField(default=False)),
                ('calage_deg', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('titre_cas', models.CharField(blank=True, max_length=100)),
                ('lien_xml', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
