# Generated by Django 4.2.18 on 2025-09-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_aube'),
    ]

    operations = [
        migrations.AddField(
            model_name='aube',
            name='revue_aube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.revueaube'),
        ),
    ]
