# Generated by Django 4.2.18 on 2025-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_aube_revue_aube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aube',
            name='projet_version_aube',
        ),
        migrations.AddField(
            model_name='aube',
            name='aube',
            field=models.CharField(blank=True, default='S1AB', max_length=100),
        ),
        migrations.AddField(
            model_name='aube',
            name='projet',
            field=models.CharField(blank=True, default='CME3', max_length=100),
        ),
        migrations.AddField(
            model_name='aube',
            name='version',
            field=models.CharField(blank=True, default='S1', max_length=100),
        ),
    ]
