# Generated by Django 4.2.18 on 2025-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_aube_projet_version_aube_aube_aube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aube',
            name='work_dir',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple')], default='red', max_length=20),
        ),
    ]
