# Generated by Django 4.2.18 on 2025-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_aube_work_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aube',
            name='work_dir',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
