# Generated by Django 4.2.18 on 2025-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_aube_work_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aube',
            name='work_dir',
        ),
        migrations.RemoveField(
            model_name='revueaube',
            name='directory',
        ),
        migrations.AddField(
            model_name='revueaube',
            name='work_dir',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
