# Generated by Django 4.2.18 on 2025-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_aube_work_dir_remove_revueaube_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aube',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
