# Generated by Django 4.2.18 on 2025-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_aube_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='revueaube',
            name='dico_genepi_auto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
