# Generated by Django 4.2.18 on 2025-10-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_revueaube_dico_genepi_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isovitesse',
            name='etat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.etat'),
        ),
        migrations.AlterField(
            model_name='revueaube',
            name='dico_genepi_auto',
            field=models.CharField(default='\\\\nas23\\YRKC\\02_Methodes_et_Outils\\03_Outils\\03_Moyenne_Fidelite_CFD\\03_Postprocessing\\TRUNKS\\codes\\GenepiAuto\\GENEPIAuto_Dico.py', max_length=255),
        ),
    ]
