# Generated by Django 4.2.18 on 2025-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_isovitesse_etat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aube',
            name='couleur',
        ),
        migrations.AddField(
            model_name='aube',
            name='color',
            field=models.CharField(default='black', max_length=255),
        ),
        migrations.AlterField(
            model_name='revueaube',
            name='dico_genepi_auto',
            field=models.CharField(default='apps\\main\\modules\\genepi\\GENEPIAuto_Dico - TRUNKS - Defaut .py', max_length=255),
        ),
    ]
