# Generated by Django 4.2.18 on 2025-10-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_aube_couleur_aube_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aube',
            name='color',
            field=models.CharField(blank=True, default='black', max_length=255),
        ),
    ]
