# Generated by Django 4.2.18 on 2025-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_aube_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revueaube',
            name='dico_genepi_auto',
            field=models.CharField(default='/apps/main/modules/genepi/GENEPIAuto_Dico - TRUNKS - Defaut .py', max_length=255),
        ),
    ]
