# Generated by Django 4.2.18 on 2025-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_revueaube_dico_genepi_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revueaube',
            name='dico_genepi_auto',
            field=models.CharField(default='\\src\\apps\\main\\modules\\genepi\\GENEPIAuto_Dico - TRUNKS - Defaut .py', max_length=255),
        ),
    ]
