# Generated by Django 4.2.18 on 2025-10-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_revueaube_dico_genepi_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aube',
            name='type_coupe_nbre_ldc',
            field=models.CharField(blank=True, default='CQ', max_length=50),
        ),
        migrations.AlterField(
            model_name='revueaube',
            name='dico_genepi_auto',
            field=models.CharField(default='apps/main/modules/genepi/GENEPIAuto_Dico - TRUNKS - Defaut .py', max_length=255),
        ),
    ]
