# Generated by Django 4.2.18 on 2025-10-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_aube_type_coupe_nbre_ldc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetShenron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_dir', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
