# Generated by Django 4.2.18 on 2025-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_projetshenron'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitaireconfiguration',
            name='genepi_auto_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
